<?php
$post = array (
  'moduleid' => '5',
  'title' => '月季花苗月季花玫瑰花苗玫瑰品种齐全包品种包活满28元包邮',
  'content' => '<p>品种：黄金宝树</p> <p>落叶与否：常绿性</p> <p>株高：1.2（m） </p> <p>胸径：3（cm） </p> <p>是否古树：否</p> <p>栽培环境：露地</p> <p>是否移植苗：是</p> <p>树形：特殊造型</p> <p>园林用途：行道树,风景树,庭荫树,防护树,湿地绿化</p> <p>主要观赏部位：观叶</p> ',
  'key' => 'd8f63kd0',
  'unit' => '棵',
  'price' => '35.00',
  'minamount' => '1',
  'company' => '福建瑞明园艺',
  'areaname' => '福建 漳浦县',
  'areaname2' => '福建 漳州',
  'truename' => '翁瑞明',
  'mobile' => '18759620839',
  'telephone' => '',
  'ali' => 'asd328984634',
  'address' => '福建-漳浦县 东南花都旁',
  //'catid' => '4',
  //'catname' => '苗木',
  'q' => '玫瑰',
  'cached' => '2013-7-12',
  'fromurl' => 'http://test.com/PageUrl.html',
);
